name: Publish Docker images to GitHub Packages

on:
  push:
    branches:
      - main

jobs:

  build-and-push-image-bot:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
              
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Packages registry
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for bot
        run: |
          docker build -f Dockerfile -t my-personal-website .

      - name: Tag and push bot image
        run: |
          docker tag my-personal-website:latest ghcr.io/${{ github.repository_owner }}/my-personal-website:latest
          docker push ghcr.io/${{ github.repository_owner }}/my-personal-website:latest
